#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATTTTSHackTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ConnectToCar")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalendarEvent(CalendarEvent instance);
    partial void UpdateCalendarEvent(CalendarEvent instance);
    partial void DeleteCalendarEvent(CalendarEvent instance);
    partial void InsertVehicleLocation(VehicleLocation instance);
    partial void UpdateVehicleLocation(VehicleLocation instance);
    partial void DeleteVehicleLocation(VehicleLocation instance);
    partial void InsertResponse(Response instance);
    partial void UpdateResponse(Response instance);
    partial void DeleteResponse(Response instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectToCarConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CalendarEvent> CalendarEvents
		{
			get
			{
				return this.GetTable<CalendarEvent>();
			}
		}
		
		public System.Data.Linq.Table<VehicleLocation> VehicleLocations
		{
			get
			{
				return this.GetTable<VehicleLocation>();
			}
		}
		
		public System.Data.Linq.Table<Response> Responses
		{
			get
			{
				return this.GetTable<Response>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarEvents")]
	public partial class CalendarEvent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CalendarEventGUID;
		
		private string _RecipName;
		
		private string _RecipPhoneNumber;
		
		private string _RecipEmailAddress;
		
		private decimal _MeetingLatitude;
		
		private decimal _MeetingLongitude;
		
		private System.DateTime _MeetingDateTime;
		
		private string _NotificationSent;
		
		private int _MinutesToArrive;
		
		private string _SenderName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalendarEventGUIDChanging(string value);
    partial void OnCalendarEventGUIDChanged();
    partial void OnRecipNameChanging(string value);
    partial void OnRecipNameChanged();
    partial void OnRecipPhoneNumberChanging(string value);
    partial void OnRecipPhoneNumberChanged();
    partial void OnRecipEmailAddressChanging(string value);
    partial void OnRecipEmailAddressChanged();
    partial void OnMeetingLatitudeChanging(decimal value);
    partial void OnMeetingLatitudeChanged();
    partial void OnMeetingLongitudeChanging(decimal value);
    partial void OnMeetingLongitudeChanged();
    partial void OnMeetingDateTimeChanging(System.DateTime value);
    partial void OnMeetingDateTimeChanged();
    partial void OnNotificationSentChanging(string value);
    partial void OnNotificationSentChanged();
    partial void OnMinutesToArriveChanging(int value);
    partial void OnMinutesToArriveChanged();
    partial void OnSenderNameChanging(string value);
    partial void OnSenderNameChanged();
    #endregion
		
		public CalendarEvent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarEventGUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CalendarEventGUID
		{
			get
			{
				return this._CalendarEventGUID;
			}
			set
			{
				if ((this._CalendarEventGUID != value))
				{
					this.OnCalendarEventGUIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarEventGUID = value;
					this.SendPropertyChanged("CalendarEventGUID");
					this.OnCalendarEventGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string RecipName
		{
			get
			{
				return this._RecipName;
			}
			set
			{
				if ((this._RecipName != value))
				{
					this.OnRecipNameChanging(value);
					this.SendPropertyChanging();
					this._RecipName = value;
					this.SendPropertyChanged("RecipName");
					this.OnRecipNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipPhoneNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipPhoneNumber
		{
			get
			{
				return this._RecipPhoneNumber;
			}
			set
			{
				if ((this._RecipPhoneNumber != value))
				{
					this.OnRecipPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._RecipPhoneNumber = value;
					this.SendPropertyChanged("RecipPhoneNumber");
					this.OnRecipPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipEmailAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RecipEmailAddress
		{
			get
			{
				return this._RecipEmailAddress;
			}
			set
			{
				if ((this._RecipEmailAddress != value))
				{
					this.OnRecipEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._RecipEmailAddress = value;
					this.SendPropertyChanged("RecipEmailAddress");
					this.OnRecipEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeetingLatitude", DbType="Decimal(18,6) NOT NULL")]
		public decimal MeetingLatitude
		{
			get
			{
				return this._MeetingLatitude;
			}
			set
			{
				if ((this._MeetingLatitude != value))
				{
					this.OnMeetingLatitudeChanging(value);
					this.SendPropertyChanging();
					this._MeetingLatitude = value;
					this.SendPropertyChanged("MeetingLatitude");
					this.OnMeetingLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeetingLongitude", DbType="Decimal(18,6) NOT NULL")]
		public decimal MeetingLongitude
		{
			get
			{
				return this._MeetingLongitude;
			}
			set
			{
				if ((this._MeetingLongitude != value))
				{
					this.OnMeetingLongitudeChanging(value);
					this.SendPropertyChanging();
					this._MeetingLongitude = value;
					this.SendPropertyChanged("MeetingLongitude");
					this.OnMeetingLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeetingDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime MeetingDateTime
		{
			get
			{
				return this._MeetingDateTime;
			}
			set
			{
				if ((this._MeetingDateTime != value))
				{
					this.OnMeetingDateTimeChanging(value);
					this.SendPropertyChanging();
					this._MeetingDateTime = value;
					this.SendPropertyChanged("MeetingDateTime");
					this.OnMeetingDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotificationSent", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NotificationSent
		{
			get
			{
				return this._NotificationSent;
			}
			set
			{
				if ((this._NotificationSent != value))
				{
					this.OnNotificationSentChanging(value);
					this.SendPropertyChanging();
					this._NotificationSent = value;
					this.SendPropertyChanged("NotificationSent");
					this.OnNotificationSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinutesToArrive", DbType="Int NOT NULL")]
		public int MinutesToArrive
		{
			get
			{
				return this._MinutesToArrive;
			}
			set
			{
				if ((this._MinutesToArrive != value))
				{
					this.OnMinutesToArriveChanging(value);
					this.SendPropertyChanging();
					this._MinutesToArrive = value;
					this.SendPropertyChanged("MinutesToArrive");
					this.OnMinutesToArriveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string SenderName
		{
			get
			{
				return this._SenderName;
			}
			set
			{
				if ((this._SenderName != value))
				{
					this.OnSenderNameChanging(value);
					this.SendPropertyChanging();
					this._SenderName = value;
					this.SendPropertyChanged("SenderName");
					this.OnSenderNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VehicleLocation")]
	public partial class VehicleLocation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _locationID;
		
		private string _vehicleGUID;
		
		private System.DateTime _dateTimeStamp;
		
		private decimal _lat;
		
		private decimal _lng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlocationIDChanging(int value);
    partial void OnlocationIDChanged();
    partial void OnvehicleGUIDChanging(string value);
    partial void OnvehicleGUIDChanged();
    partial void OndateTimeStampChanging(System.DateTime value);
    partial void OndateTimeStampChanged();
    partial void OnlatChanging(decimal value);
    partial void OnlatChanged();
    partial void OnlngChanging(decimal value);
    partial void OnlngChanged();
    #endregion
		
		public VehicleLocation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int locationID
		{
			get
			{
				return this._locationID;
			}
			set
			{
				if ((this._locationID != value))
				{
					this.OnlocationIDChanging(value);
					this.SendPropertyChanging();
					this._locationID = value;
					this.SendPropertyChanged("locationID");
					this.OnlocationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleGUID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vehicleGUID
		{
			get
			{
				return this._vehicleGUID;
			}
			set
			{
				if ((this._vehicleGUID != value))
				{
					this.OnvehicleGUIDChanging(value);
					this.SendPropertyChanging();
					this._vehicleGUID = value;
					this.SendPropertyChanged("vehicleGUID");
					this.OnvehicleGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateTimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime dateTimeStamp
		{
			get
			{
				return this._dateTimeStamp;
			}
			set
			{
				if ((this._dateTimeStamp != value))
				{
					this.OndateTimeStampChanging(value);
					this.SendPropertyChanging();
					this._dateTimeStamp = value;
					this.SendPropertyChanged("dateTimeStamp");
					this.OndateTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(14,8) NOT NULL")]
		public decimal lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Decimal(14,8) NOT NULL")]
		public decimal lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Responses")]
	public partial class Response : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ResponseGUID;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResponseGUIDChanging(string value);
    partial void OnResponseGUIDChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Response()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResponseGUID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ResponseGUID
		{
			get
			{
				return this._ResponseGUID;
			}
			set
			{
				if ((this._ResponseGUID != value))
				{
					this.OnResponseGUIDChanging(value);
					this.SendPropertyChanging();
					this._ResponseGUID = value;
					this.SendPropertyChanged("ResponseGUID");
					this.OnResponseGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
